"use client";

import { useEffect } from 'react';

export default function RegisterServiceWorker() {
  useEffect(() => {
    if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return;

    // Don't register on the root landing page
    if (window.location.pathname === '/') return;

    let mounted = true;

    const register = async () => {
      try {
        // register the SW generated by next-pwa (sw.js in public)
        const reg = await navigator.serviceWorker.register('/sw.js', {
          scope: '/login'
        });
        if (!mounted) return;
        // optional: listen for updates
        reg.addEventListener?.('updatefound', () => {
          // handle updates if desired
          const installing = reg.installing;
          installing?.addEventListener('statechange', () => {
            // noop for now
          });
        });
      } catch (err) {
        // registration failed; ignore silently
        // console.warn('SW registration failed', err);
      }
    };

    // Only register when on a route that intends to be PWA-enabled.
    register();

    return () => {
      mounted = false;
    };
  }, []);

  return null;
}
